---
title: "R Notebook"
output: html_notebook
---

#### 1.1 load data and create object

```{r}
library(PIDC)
library(scATFR)
exp_data <- readRDS(system.file("./inst/extdata/mouse_HSC_formation_expression.rds",package = "scATFR"))
col_metadata <- readRDS(system.file("./inst/extdata/mouse_HSC_formation_colData.rds",package = "scATFR"))
row.names(col_metadata) <- col_metadata$sample
atfr <- scATFR(exp_data = exp_data,col_data = col_metadata)
```

#### 1.2 calculating the gene regulatory network

```{r}
atfr <- inferGRNs(x = atfr, method="pidc",ncores=6)
PIDC_nets <- PIDC::matToNet(weightMat = as.matrix(GRN(atfr,"pidc")), ncores = 6)
colnames(PIDC_nets) <- c("tf","target","weight")
```

#### 1.3 Integrating the gene regulatory network with TF-target sources

```{r}
library(dplyr)
TF_gene <- intersect(TF_Symbols$mouse,row.names(atfr))
pantissue_network <- readRDS(system.file("./inst/extdata/mm_pantissue_network.rds",package = "scATFR")) %>% filter(tf %in% TF_gene)
regulons <- integraNets(grnNets = list(PIDC_nets, pantissue_network), norm_weight = T,
                        max_target_num=2000, min_target_num = 100, join_type = "full", 
                        return_sig = T, maxInter = 5, ncores = 6)
interged_regulon_list <- dfToList(regulons)
atfr <- filterRegulons(x = atfr, gene_list=interged_regulon_list, maxSize=500, minSize=5)
```
#### 1.4 Inferring regulon activity

```{r}
atfr <- regulonActivity(x = atfr, method="viper")
active_mat <- assay(altExp(atfr,"viper"))
write.table(active_mat,"D:/HSC_Autophagy/Markdown/3.scATFR/ext_data/HSC_development/viper/TF_active_mat.txt",sep="\t",quote=F)
```

#### 1.5 differential regulons

```{r}
atfr <- findAllCTSRegulons(x = atfr, use_assay="viper",clust_name ="stage",ncores=6, nperm=10000)
diff_regulons <- diffRegulons(atfr)
```






